version: '3.8'

services:

  todo-app:
    image: vikyath11/todo-app-artifactory
    ports:
      - "3001:3001"
    deploy:
      placement:
        constraints:
          - node.labels.type == todoworker

  calc-app:
    image: vikyath11/vikyath-artifactory
    ports:
      - "3000:3000"
    deploy:
      placement:
        constraints:
          - node.labels.type == worker

  mongodbcont:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db
    deploy:
      placement:
        constraints:
          - node.labels.type == todoworker

volumes:
  mongodb-data:
