version: '3'

services:

  todo-app:
    image: vikyath11/todo-app-artifactory
    ports:
      - "3001:3001"

  calc-app:
    image: vikyath11/vikyath-artifactory
    ports:
      - "3000:3000"

  mongodbcont:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db

volumes:
  mongodb-data:
